"""Stitch tiles into a single image. 

Usage: 
    TileStitcher(
        input_tile_dir, 
        output_tile_dir, 
        output_format='png').stitch()

Sample input: 
    input_tile_dir/
    ├── images/
    │   ├── Gavihalla_x0_y0.png
    │   ├── Gavihalla_x384_y0.png
    └── tiles_metadata.json

    output_tile_dir/
    ├── inference_Gavihalla_x0_y0.png
    ├── ...    
    └── inference_Gavihalla_x384_y0.png

Sample output: 
    output_tile_dir/
    ├── inference_Gavihalla_x0_y0.png
    ├── ...
    ├── inference_Gavihalla_x384_y0.png    
    └── Gavihalla_stitched.png

For example to simply re-stitch all the input tiles, you can run: 
TileStitcher(
    input_tile_dir="input_tile_dir",
    output_tile_dir="input_tile_dir/images",
    output_format="png",
    preview_scale_factor=0.1
).stitch()

And look for the stitched site images in the output_tile_dir/images directory. 

In other words the output_tile_dir is both the base directory for inputs *into* the final mosaic, as well as the directory into which the final mosaic is saved. If the tiles are not found in the output_tile_dir, the stitcher will look for them in the input_tile_dir/images directory. 

A note on preview images: 

The preview images are generated by downscaling the full images by a scale 
factor. 

| Scale Factor | Pixel Size  | % of Original Pixels | Approx File Size Drop |
| ------------ | ----------- | -------------------- | --------------------- |
| 1.0          | full size   | 100%                 | 100% (no reduction)   |
| 0.5          | half size   | 25%                  | \~75-85% smaller      |
| 0.1          | 1/10th size | 1%                   | \~95-99% smaller      |

"""

import os
import json
from PIL import Image
from tqdm import tqdm
import logging
from collections import defaultdict
from tiling.bounds import BoundsConverter

# Get module-level logger
logger = logging.getLogger(__name__)

# Disable PIL's max image pixels limit.
Image.MAX_IMAGE_PIXELS = None


class TileStitcher:
    def __init__(self, input_tile_dir, output_tile_dir, output_format='png', map_preview_scale_factor=0.1, tile_preview_scale_factor=None):
        self.input_tile_dir = input_tile_dir
        self.output_tile_dir = output_tile_dir
        self.output_format = output_format
        self.map_preview_scale_factor = map_preview_scale_factor
        self.tile_preview_scale_factor = tile_preview_scale_factor

        self.metadata_path = os.path.join(
            self.input_tile_dir, "tiles_metadata.json")
        self.input_images_dir = os.path.join(self.input_tile_dir, "images")

        if not os.path.exists(self.metadata_path):
            raise FileNotFoundError(
                f"Missing tiles_metadata.json at {self.metadata_path}")

        self.tile_metadata = self._load_metadata()
        self.tile_size = None
        self.step_size = None
        self.output_image_files = [
            f for f in os.listdir(self.output_tile_dir)]
        self.output_json_files = [
            f for f in os.listdir(self.output_tile_dir) if f.endswith('.json')]

    def _load_metadata(self):
        with open(self.metadata_path, 'r') as f:
            return json.load(f)

    def _get_tile_size(self):
        """Get the size of tiles in the input directory. 

        This function makes a few assumptions: 
          1. All tiles are the same size (all input tiles, and input tiles are the same size as output tiles). 
          2. All tiles are square. 

        Returns: 
            tile_size: int, the size of the tiles in the input directory. 
        """
        for tile in self.tile_metadata:
            tile_path = os.path.join(self.input_images_dir, tile['filename'])
            if os.path.exists(tile_path):
                with Image.open(tile_path) as img:
                    return img.size[0]
        return RuntimeError("No valid tiles found in input directory to determine tile size.")

    def _get_canvas_size(self, tiles):
        max_x, max_y = 0, 0
        for tile in tiles:
            x, y = tile['pixel_origin']
            max_x = max(max_x, x)
            max_y = max(max_y, y)
        width = max_x + self.tile_size
        height = max_y + self.tile_size
        return width, height

    def _match_output_file(self, original_filename):
        # Match based on suffix: find file ending in original_filename.
        inference_path = None
        predictions_path = None

        for fname in self.output_image_files:
            if fname.endswith(original_filename):
                inference_path = os.path.join(self.output_tile_dir, fname)
                break

        # If inference file found, look for corresponding predictions file
        if inference_path:
            # Extract the base name from the inference file (e.g., "inference_Hossur_Geratti_2_x4608_y4608.png")
            inference_basename = os.path.basename(inference_path)
            # Create the expected predictions filename (e.g., "predictions_Hossur_Geratti_2_x4608_y4608.json")
            # Handle different image extensions (png, jpg, jpeg, etc.)
            predictions_filename = inference_basename.replace(
                "inference_", "predictions_")
            # Remove the image extension and add .json
            base_name = os.path.splitext(predictions_filename)[0]
            predictions_filename = base_name + ".json"
            predictions_path = os.path.join(
                self.output_tile_dir, predictions_filename)

            # Check if predictions file exists
            if not os.path.exists(predictions_path):
                logger.warning(
                    f"Warning: Inference file found at {inference_path} but predictions file not found at {predictions_path}")
                predictions_path = None

        return inference_path, predictions_path

    def _find_input_tile_metadata(self, original_filename):
        """Find the input tile metadata for a given filename.

        Args:
            original_filename: The original tile filename to match

        Returns:
            dict: The matching tile metadata from input tiles_metadata.json, or None if not found
        """
        for tile in self.tile_metadata:
            if tile['filename'] == original_filename:
                return tile
        return None

    def _calculate_site_bounds(self, tiles):
        """Calculate the bounds of a site from its edge tiles.

        This function finds the minimum and maximum bounds from all tiles
        to determine the overall boundary of the stitched image.

        Args:
            tiles: List of tile metadata dictionaries for a site

        Returns:
            tuple: (bounds, crs) where bounds is [min_x, min_y, max_x, max_y] and crs is the coordinate system
        """
        if not tiles:
            return None, None

        # Initialize with first tile's bounds
        first_tile = tiles[0]
        min_x, min_y, max_x, max_y = first_tile['tile_bounds']
        crs = first_tile['crs']

        # Find the overall bounds by taking min/max across all tiles
        for tile in tiles:
            tile_bounds = tile['tile_bounds']
            min_x = min(min_x, tile_bounds[0])
            min_y = min(min_y, tile_bounds[1])
            max_x = max(max_x, tile_bounds[2])
            max_y = max(max_y, tile_bounds[3])

        return [min_x, min_y, max_x, max_y], crs

    @staticmethod
    def generate_preview(full_image_path, preview_image_path, scale_factor=0.1):
        """Generate a downscaled preview image from a full image.

        This function preserves aspect ratio by scaling both width and height 
        proportionally.

        Tradeoffs in image resizing:
        1. Aspect Ratio: This function maintains the original aspect ratio, 
        which is crucial for maps and images where proportions matter. 
        Distorting aspect ratio can make maps unusable for navigation or 
        analysis.

        2. File Size vs Quality: 
           - Reducing max_width decreases file size but also reduces detail
           - For 100MB to 1MB reduction, you might need max_width 100-500 pixels
           - PNG format maintains quality but larger files vs JPEG 

        @param full_image_path: Path to the full image.
        @param preview_image_path: Path to the output preview image.
        @param max_width: Maximum width of the preview map. Height is scaled proportionally.
        """
        with Image.open(full_image_path) as img:
            new_size = (
                int(img.size[0] * scale_factor),
                int(img.size[1] * scale_factor))
            preview_img = img.resize(new_size, Image.LANCZOS)
            preview_img.save(preview_image_path)

    def stitch(self):
        logger.info("Loading metadata and determining tile layout...")
        self.tile_size = self._get_tile_size()
        logger.debug(f"Tile size: {self.tile_size}")

        # Group tiles by site
        site_tiles = defaultdict(list)
        for tile in self.tile_metadata:
            site_tiles[tile['site']].append(tile)

        flat_metadata = []

        for site_name, tiles in site_tiles.items():
            logger.info(f"\nStitching site: {site_name}")
            stitched_width, stitched_height = self._get_canvas_size(tiles)
            canvas = Image.new('RGB', (stitched_width, stitched_height))

            # Calculate site bounds before processing tiles
            site_bounds, site_crs = self._calculate_site_bounds(tiles)
            site_bounds_converter = BoundsConverter(
                site_bounds, site_crs, BoundsConverter.GPS_CRS)
            site_bounds_gps = site_bounds_converter.get_bounds()
            site_center_gps = site_bounds_converter.get_center()
            site_crs_gps = site_bounds_converter.target_crs

            tile_index = 0
            for tile in tqdm(tiles):
                x, y = tile['pixel_origin']
                tile_file = tile['filename']

                # Prefer the file in the output_dir and fallback to the
                # original tile if not found.
                tile_path, predictions_path = self._match_output_file(
                    tile_file)
                if not tile_path or not os.path.exists(tile_path):
                    tile_path = os.path.join(self.input_images_dir, tile_file)
                    # If using input tile, there won't be predictions file
                    predictions_path = None

                if not os.path.exists(tile_path):
                    logger.warning(
                        f"Warning: Missing tile at {tile_path}, skipping...")
                    continue

                with Image.open(tile_path) as tile_img:
                    canvas.paste(tile_img, (x, y))

                # Generate preview for tile if requested
                tile_preview_path = None
                if self.tile_preview_scale_factor:
                    tile_preview_name = f"preview_{os.path.basename(tile_path)}"
                    tile_preview_path = os.path.join(
                        self.output_tile_dir, tile_preview_name)
                    self.generate_preview(
                        tile_path,
                        tile_preview_path,
                        self.tile_preview_scale_factor)

                # Get the original tile metadata to extract bounds and crs
                input_tile_metadata = self._find_input_tile_metadata(tile_file)
                if input_tile_metadata:
                    bounds_converter = BoundsConverter(
                        input_tile_metadata['tile_bounds'],
                        input_tile_metadata['crs'],
                        BoundsConverter.GPS_CRS)
                    bounds_gps = bounds_converter.get_bounds()
                    crs_gps = bounds_converter.target_crs
                    center_gps = bounds_converter.get_center()
                else:
                    bounds_gps = None
                    center_gps = None
                    crs_gps = None

                # TODO(gh/issue/..): add image metadata like annotations
                flat_metadata.append({
                    "image": {
                        "source": os.path.abspath(tile_path),
                        "preview": os.path.abspath(tile_preview_path) if tile_preview_path else None,
                        "predictions": os.path.abspath(predictions_path) if predictions_path else None,
                        "pixel_origin": [x, y],
                        "index": tile_index,
                        "bounds": bounds_gps,
                        # TODO(prashanth@): Ideally, we would call
                        # get_tile_size for each tile and set separately.
                        "size": self.tile_size,
                        "crs": crs_gps,
                        "center": {
                            "lon": center_gps[0],
                            "lat": center_gps[1]
                        }
                    },
                    "parent": {
                        "name": site_name,
                        "image": {}  # Will be set after stitching
                    }
                })
                tile_index += 1

            # Save the stitched image
            output_path = os.path.join(
                self.output_tile_dir, f"{site_name}_stitched.png")
            canvas.save(output_path)
            logger.info(f"Stitched image saved to: {output_path}")

            # Generate preview for stitched image if requested
            stitched_preview_path = None
            if self.map_preview_scale_factor:
                stitched_preview_name = f"preview_{site_name}_stitched.png"
                stitched_preview_path = os.path.join(
                    self.output_tile_dir, stitched_preview_name)
                self.generate_preview(
                    output_path,
                    stitched_preview_path,
                    self.map_preview_scale_factor)

            # Update all tiles for this site with the parent image info
            for metadata_item in flat_metadata:
                if metadata_item["parent"]["name"] == site_name:
                    metadata_item["parent"]["image"].update({
                        "source": os.path.abspath(output_path),
                        "preview": os.path.abspath(
                            stitched_preview_path) if stitched_preview_path else None,
                        "bounds": site_bounds_gps,
                        "crs": site_crs_gps,
                        "center": {
                            "lon": site_center_gps[0],
                            "lat": site_center_gps[1]
                        }
                    })

        stitched_metadata_path = os.path.join(
            self.output_tile_dir, "stitched_tile_metadata.json")
        with open(stitched_metadata_path, 'w') as f:
            json.dump(flat_metadata, f, indent=2)
        logger.info(f"Stitched metadata saved to: {stitched_metadata_path}")

        return stitched_metadata_path
