"""Stitch tiles into a single image. 

Usage: 
    TileStitcher(
        input_tile_dir, 
        output_tile_dir, 
        output_format='png').stitch()

Sample input: 
    input_tile_dir/
    ├── images/
    │   ├── Gavihalla_x0_y0.png
    │   ├── Gavihalla_x384_y0.png
    └── tiles_metadata.json

    output_tile_dir/
    ├── inference_Gavihalla_x0_y0.png
    ├── ...    
    └── inference_Gavihalla_x384_y0.png

Sample output: 
    output_tile_dir/
    ├── inference_Gavihalla_x0_y0.png
    ├── ...
    ├── inference_Gavihalla_x384_y0.png    
    └── Gavihalla_stitched.png

For example to simply re-stitch all the input tiles, you can run: 
TileStitcher(
    input_tile_dir="input_tile_dir",
    output_tile_dir="input_tile_dir/images",
    output_format="png",
    preview_scale_factor=0.1
).stitch()

And look for the stitched site images in the output_tile_dir/images directory. 

In other words the output_tile_dir is both the base directory for inputs *into* the final mosaic, as well as the directory into which the final mosaic is saved. If the tiles are not found in the output_tile_dir, the stitcher will look for them in the input_tile_dir/images directory. 

A note on preview images: 

The preview images are generated by downscaling the full images by a scale 
factor. 

| Scale Factor | Pixel Size  | % of Original Pixels | Approx File Size Drop |
| ------------ | ----------- | -------------------- | --------------------- |
| 1.0          | full size   | 100%                 | 100% (no reduction)   |
| 0.5          | half size   | 25%                  | \~75-85% smaller      |
| 0.1          | 1/10th size | 1%                   | \~95-99% smaller      |

"""

import os
import json
from PIL import Image
from tqdm import tqdm
import logging
from collections import defaultdict

# Get module-level logger
logger = logging.getLogger(__name__)

# Disable PIL's max image pixels limit.
Image.MAX_IMAGE_PIXELS = None


class TileStitcher:
    def __init__(self, input_tile_dir, output_tile_dir, output_format='png', map_preview_scale_factor=0.1, tile_preview_scale_factor=None):
        self.input_tile_dir = input_tile_dir
        self.output_tile_dir = output_tile_dir
        self.output_format = output_format
        self.map_preview_scale_factor = map_preview_scale_factor
        self.tile_preview_scale_factor = tile_preview_scale_factor

        self.metadata_path = os.path.join(
            self.input_tile_dir, "tiles_metadata.json")
        self.input_images_dir = os.path.join(self.input_tile_dir, "images")

        if not os.path.exists(self.metadata_path):
            raise FileNotFoundError(
                f"Missing tiles_metadata.json at {self.metadata_path}")

        self.tile_metadata = self._load_metadata()
        self.tile_size = None
        self.step_size = None
        self.output_image_files = [
            f for f in os.listdir(self.output_tile_dir)]

    def _load_metadata(self):
        with open(self.metadata_path, 'r') as f:
            return json.load(f)

    def _get_tile_size(self):
        """Get the size of tiles in the input directory. 

        This function makes a few assumptions: 
          1. All tiles are the same size (all input tiles, and input tiles are the same size as output tiles). 
          2. All tiles are square. 

        Returns: 
            tile_size: int, the size of the tiles in the input directory. 
        """
        for tile in self.tile_metadata:
            tile_path = os.path.join(self.input_images_dir, tile['filename'])
            if os.path.exists(tile_path):
                with Image.open(tile_path) as img:
                    self.tile_size = img.size[0]
                    return
        return RuntimeError("No valid tiles found in input directory to determine tile size.")

    def _get_canvas_size(self, tiles):
        max_x, max_y = 0, 0
        for tile in tiles:
            x, y = tile['pixel_origin']
            max_x = max(max_x, x)
            max_y = max(max_y, y)
        width = max_x + self.tile_size
        height = max_y + self.tile_size
        return width, height

    def _match_output_file(self, original_filename):
        # Match based on suffix: find file ending in original_filename.
        for fname in self.output_image_files:
            if fname.endswith(original_filename):
                return os.path.join(self.output_tile_dir, fname)
        return None

    @staticmethod
    def generate_preview(full_image_path, preview_image_path, scale_factor=0.1):
        """Generate a downscaled preview image from a full image.

        This function preserves aspect ratio by scaling both width and height 
        proportionally.

        Tradeoffs in image resizing:
        1. Aspect Ratio: This function maintains the original aspect ratio, 
        which is crucial for maps and images where proportions matter. 
        Distorting aspect ratio can make maps unusable for navigation or 
        analysis.

        2. File Size vs Quality: 
           - Reducing max_width decreases file size but also reduces detail
           - For 100MB to 1MB reduction, you might need max_width 100-500 pixels
           - PNG format maintains quality but larger files vs JPEG 

        @param full_image_path: Path to the full image.
        @param preview_image_path: Path to the output preview image.
        @param max_width: Maximum width of the preview map. Height is scaled proportionally.
        """
        with Image.open(full_image_path) as img:
            new_size = (
                int(img.size[0] * scale_factor),
                int(img.size[1] * scale_factor))
            preview_img = img.resize(new_size, Image.LANCZOS)
            preview_img.save(preview_image_path)

    def stitch(self):
        logger.info("Loading metadata and determining tile layout...")
        self._get_tile_size()
        logger.debug(f"Tile size: {self.tile_size}")

        # Group tiles by site
        site_tiles = defaultdict(list)
        for tile in self.tile_metadata:
            site_tiles[tile['site']].append(tile)

        flat_metadata = []

        for site_name, tiles in site_tiles.items():
            logger.info(f"\nStitching site: {site_name}")
            stitched_width, stitched_height = self._get_canvas_size(tiles)
            canvas = Image.new('RGB', (stitched_width, stitched_height))

            tile_index = 0
            for tile in tqdm(tiles):
                x, y = tile['pixel_origin']
                tile_file = tile['filename']

                # Prefer the file in the output_dir and fallback to the
                # original tile if not found.
                output_tile_path = self._match_output_file(tile_file)
                tile_path = output_tile_path

                if not tile_path or not os.path.exists(tile_path):
                    tile_path = os.path.join(self.input_images_dir, tile_file)

                if not os.path.exists(tile_path):
                    logger.warning(
                        f"Warning: Missing tile at {tile_path}, skipping...")
                    continue

                with Image.open(tile_path) as tile_img:
                    canvas.paste(tile_img, (x, y))

                # Generate preview for tile if requested
                tile_preview_path = None
                if self.tile_preview_scale_factor:
                    tile_preview_name = f"preview_{os.path.basename(tile_path)}"
                    tile_preview_path = os.path.join(
                        self.output_tile_dir, tile_preview_name)
                    self.generate_preview(
                        tile_path,
                        tile_preview_path,
                        self.tile_preview_scale_factor)

                # TODO(gh/issue/..): add image metadata like annotations
                flat_metadata.append({
                    "image": {
                        "source": os.path.abspath(tile_path),
                        "preview": os.path.abspath(tile_preview_path) if tile_preview_path else None,
                        "origin": [x, y],
                        "index": tile_index
                    },
                    "parent": {
                        "name": site_name,
                        "image": {
                            "source": None,  # Will be set after stitching
                            "preview": None  # Will be set after stitching
                        }
                    }
                })
                tile_index += 1

            # Save the stitched image
            output_path = os.path.join(
                self.output_tile_dir, f"{site_name}_stitched.png")
            canvas.save(output_path)
            logger.info(f"Stitched image saved to: {output_path}")

            # Generate preview for stitched image if requested
            stitched_preview_path = None
            if self.map_preview_scale_factor:
                stitched_preview_name = f"preview_{site_name}_stitched.png"
                stitched_preview_path = os.path.join(
                    self.output_tile_dir, stitched_preview_name)
                self.generate_preview(
                    output_path,
                    stitched_preview_path,
                    self.map_preview_scale_factor)

            # Update all tiles for this site with the parent image info
            for metadata_item in flat_metadata:
                if metadata_item["parent"]["name"] == site_name:
                    metadata_item["parent"]["image"]["source"] = os.path.abspath(
                        output_path)
                    metadata_item["parent"]["image"]["preview"] = os.path.abspath(
                        stitched_preview_path) if stitched_preview_path else None

        inference_metadata_path = os.path.join(
            self.output_tile_dir, "inference_tile_metadata.json")
        with open(inference_metadata_path, 'w') as f:
            json.dump(flat_metadata, f, indent=2)
        logger.info(f"Inference metadata saved to: {inference_metadata_path}")

        return inference_metadata_path
